### ISSUE TITLE
cause the generator of KEDMI and GMI are not cGAN，how can I konw the recovery result of specific class?Or I should use the target model to select by myself?

### ISSUE THREAD

**Issue by nevereverforget1** [LetheSec/PLG-MI-Attack#1]

**Comment by LetheSec** [comment]
The class is specified in the loss function of the stage 2 (L_inv).  You can refer to the formula (1) of the paper.

**Comment by nevereverforget1** [comment]
我表达的不够清楚，我是说KED-MI和GMI的恢复之后的图片没有按类别分，我没办法像图4那样去按类别比较，但是我用target model 把恢复的图片重新分类了，这是可行的。
谢谢你的回答
