### ISSUE TITLE
Isn't training the cGAN with a private dataset already considered a privacy leak?

### ISSUE THREAD

**Issue by EchoLymmm** [LetheSec/PLG-MI-Attack#3]
During the training of the cGAN, the real images used as input for the discriminator come from a private dataset that I want to protect. If I already know the contents of the private dataset during the training process, why would I still want to attack it? How can the attacker have access to the private dataset？

**Comment by LetheSec** [comment]
Thanks for your interest in our work. 

The real images used when training cGAN are from public data, not the private dataset.

**Comment by EchoLymmm** [comment]
> Thanks for your interest in our work.
> 
> The real images used when training cGAN are from public data, not the private dataset.

Sorry, I didn’t review the code closely regarding the dataset used for training the GAN.Thank you for your response！
